//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/app/src/main/java/net/iseteki/j2objcsample/library/Program.java
//


#include "J2ObjC_source.h"
#include "Program.h"
#include "java/util/List.h"

@interface EBIAnimeProgram () {
 @public
  NSString *name_;
  id<JavaUtilList> subTitles_;
}

@end

J2OBJC_FIELD_SETTER(EBIAnimeProgram, name_, NSString *)
J2OBJC_FIELD_SETTER(EBIAnimeProgram, subTitles_, id<JavaUtilList>)

@implementation EBIAnimeProgram

- (instancetype)initWithName:(NSString *)name
                   subTitles:(id<JavaUtilList>)subTitles {
  EBIAnimeProgram_initWithName_subTitles_(self, name, subTitles);
  return self;
}

- (NSString *)name {
  return name_;
}

- (void)setName:(NSString *)name {
  self->name_ = name;
}

- (id<JavaUtilList>)subTitles {
  return subTitles_;
}

- (void)setSubTitles:(id<JavaUtilList>)subTitles {
  self->subTitles_ = subTitles;
}

- (NSString *)description {
  return JreStrcat("$$$", @"Program{name='", name_, @"'}");
}

@end

void EBIAnimeProgram_initWithName_subTitles_(EBIAnimeProgram *self, NSString *name, id<JavaUtilList> subTitles) {
  (void) NSObject_init(self);
  self->name_ = name;
  self->subTitles_ = subTitles;
}

EBIAnimeProgram *new_EBIAnimeProgram_initWithName_subTitles_(NSString *name, id<JavaUtilList> subTitles) {
  EBIAnimeProgram *self = [EBIAnimeProgram alloc];
  EBIAnimeProgram_initWithName_subTitles_(self, name, subTitles);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EBIAnimeProgram)
