//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/app/src/main/java/net/iseteki/j2objcsample/library/Program.java
//

#ifndef _NetIsetekiJ2objcsampleLibraryProgram_H_
#define _NetIsetekiJ2objcsampleLibraryProgram_H_

#include "J2ObjC_header.h"

@protocol JavaUtilList;

@interface EBIAnimeProgram : NSObject

#pragma mark Public

- (instancetype)initWithName:(NSString *)name
                   subTitles:(id<JavaUtilList>)subTitles;

- (NSString *)name;

- (id<JavaUtilList>)subTitles;

- (void)setName:(NSString *)name;

- (void)setSubTitles:(id<JavaUtilList>)subTitles;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(EBIAnimeProgram)

FOUNDATION_EXPORT void EBIAnimeProgram_initWithName_subTitles_(EBIAnimeProgram *self, NSString *name, id<JavaUtilList> subTitles);

FOUNDATION_EXPORT EBIAnimeProgram *new_EBIAnimeProgram_initWithName_subTitles_(NSString *name, id<JavaUtilList> subTitles) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(EBIAnimeProgram)

typedef EBIAnimeProgram NetIsetekiJ2objcsampleLibraryProgram;

#endif // _NetIsetekiJ2objcsampleLibraryProgram_H_
