//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android/app/src/main/java/net/iseteki/j2objcsample/library/SubTitle.java
//

#ifndef _NetIsetekiJ2objcsampleLibrarySubTitle_H_
#define _NetIsetekiJ2objcsampleLibrarySubTitle_H_

#include "J2ObjC_header.h"

@interface EBIAnimeSubTitle : NSObject {
 @public
  jint countNumber_;
  NSString *name_;
}

#pragma mark Public

- (instancetype)initWithCountNumber:(jint)countNumber
                               name:(NSString *)name;

- (jint)countNumber;

- (NSString *)name;

- (void)setCountNumber:(jint)countNumber;

- (void)setName:(NSString *)name;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(EBIAnimeSubTitle)

J2OBJC_FIELD_SETTER(EBIAnimeSubTitle, name_, NSString *)

FOUNDATION_EXPORT void EBIAnimeSubTitle_initWithCountNumber_name_(EBIAnimeSubTitle *self, jint countNumber, NSString *name);

FOUNDATION_EXPORT EBIAnimeSubTitle *new_EBIAnimeSubTitle_initWithCountNumber_name_(jint countNumber, NSString *name) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(EBIAnimeSubTitle)

typedef EBIAnimeSubTitle NetIsetekiJ2objcsampleLibrarySubTitle;

#endif // _NetIsetekiJ2objcsampleLibrarySubTitle_H_
